"""Event type registry for PR39/PR40/PR43 domain events."""

from __future__ import annotations

EVENT_BID_CREATED = "bid.created"
EVENT_BID_UPDATED = "bid.updated"
EVENT_BID_DELETED = "bid.deleted"
EVENT_BID_ACCEPTED = "bid.accepted"
EVENT_HANDSHAKE_CANCELLED = "handshake.cancelled"
EVENT_HANDSHAKE_ACCEPTED = "handshake.accepted"
EVENT_HANDSHAKE_REJECTED = "handshake.rejected"
EVENT_BOOKING_CANCELLED_BY_CUSTOMER = "booking.cancelled_by_customer"
EVENT_DRIVER_ASSIGNMENT_CHANGED = "driver.assignment_changed"
EVENT_REQUEST_CREATED = "request.created"

SCHEMA_VERSION_V1 = 1
AGGREGATE_REQUEST = "request"

# Dual-registry with openbid-worker/event_pipeline/registry.py — keep in sync.
SUPPORTED_EVENT_TYPES = frozenset(
    {
        EVENT_BID_CREATED,
        EVENT_BID_UPDATED,
        EVENT_BID_DELETED,
        EVENT_BID_ACCEPTED,
        EVENT_HANDSHAKE_CANCELLED,
        EVENT_HANDSHAKE_ACCEPTED,
        EVENT_HANDSHAKE_REJECTED,
        EVENT_BOOKING_CANCELLED_BY_CUSTOMER,
        EVENT_DRIVER_ASSIGNMENT_CHANGED,
        EVENT_REQUEST_CREATED,
    }
)
SUPPORTED_SCHEMA_VERSIONS = frozenset({SCHEMA_VERSION_V1})

# Per-event env flag names (defaults false). Master: DOMAIN_EVENTS_ENABLED.
EVENT_TYPE_FLAG_ENV = {
    EVENT_BID_CREATED: "DOMAIN_EVENT_BID_CREATED_ENABLED",
    EVENT_BID_UPDATED: "DOMAIN_EVENT_BID_UPDATED_ENABLED",
    EVENT_BID_DELETED: "DOMAIN_EVENT_BID_DELETED_ENABLED",
    EVENT_BID_ACCEPTED: "DOMAIN_EVENT_BID_ACCEPTED_ENABLED",
    EVENT_HANDSHAKE_CANCELLED: "DOMAIN_EVENT_HANDSHAKE_CANCELLED_ENABLED",
    EVENT_HANDSHAKE_ACCEPTED: "DOMAIN_EVENT_HANDSHAKE_ACCEPTED_ENABLED",
    EVENT_HANDSHAKE_REJECTED: "DOMAIN_EVENT_HANDSHAKE_REJECTED_ENABLED",
    EVENT_BOOKING_CANCELLED_BY_CUSTOMER: (
        "DOMAIN_EVENT_BOOKING_CANCELLED_BY_CUSTOMER_ENABLED"
    ),
    EVENT_DRIVER_ASSIGNMENT_CHANGED: (
        "DOMAIN_EVENT_DRIVER_ASSIGNMENT_CHANGED_ENABLED"
    ),
    EVENT_REQUEST_CREATED: "DOMAIN_EVENT_REQUEST_CREATED_ENABLED",
}

OUTBOX_STATUS_PENDING = "pending"
OUTBOX_STATUS_PUBLISHED = "published"
OUTBOX_STATUS_DEAD = "dead"
OUTBOX_STATUSES = frozenset(
    {OUTBOX_STATUS_PENDING, OUTBOX_STATUS_PUBLISHED, OUTBOX_STATUS_DEAD}
)


def validate_event_type(event_type: str) -> None:
    if event_type not in SUPPORTED_EVENT_TYPES:
        raise ValueError(f"unsupported eventType: {event_type}")


def validate_schema_version(version: int) -> None:
    if version not in SUPPORTED_SCHEMA_VERSIONS:
        raise ValueError(f"unsupported schemaVersion: {version}")
